services:
  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: auth-sys

    ports:
      - "${PORT}:${PORT}"

    env_file:
      - .env

    depends_on:
      - mysql

    restart: unless-stopped

  mysql:
    image: mysql:8

    container_name: auth-mysql

    env_file:
      - .env

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    restart: unless-stopped

volumes:
  mysql_data: